version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      # Ensure Git is initialized and fetch full history
      - echo "Initializing Git repository and fetching full history"
      - git init --initial-branch=main
      - git remote add origin https://github.com/avish747/TestClientProject.git
      - git fetch origin
      - git log --oneline --all
      - git fetch --all
      - git status

  pre_build:
    commands:
      # Define the file to check for changes
      - FILE="test_client_project/data/test.json"
      # Check if the specified file has changed between the latest commit (HEAD) and the previous commit (HEAD~1)
      - echo "Checking if the file has changed"
      - git diff --name-only
      - if git diff --name-only | grep -q "$FILE"; then
          export FILE_CHANGED=true;
        else
          export FILE_CHANGED=false;
        fi

  build:
    commands:
      # Upload the file to S3 only if it has changed
      - if [ "$FILE_CHANGED" = true ]; then
          echo "File has changed. Uploading $FILE to S3...";
          aws s3 cp $FILE s3://test-client-project/source_ip_file/test.json;
        else
          echo "$FILE has not changed. Skipping upload.";
        fi

artifacts:
  files:
    - test_client_project/data/test.json  # Optionally include the file in artifacts if needed
