version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Starting build to upload file to S3"
      # Fetch full history to ensure HEAD^ is available
      - git fetch --unshallow || true

  pre_build:
    commands:
      - FILE="test_client_project/data/test.json"
      - if git diff --name-only HEAD^ HEAD | grep -q "$FILE"; then
          export FILE_CHANGED=true;
        else
          export FILE_CHANGED=false;
        fi

  build:
    commands:
      - if [ "$FILE_CHANGED" = true ]; then
          echo "Uploading $FILE to S3...";
          aws s3 cp $FILE s3://test-client-project/source_ip_file/test.json;
        else
          echo "$FILE has not changed. Skipping upload.";
        fi
