# .github/workflows/upload-test-json-to-s3.yml
name: Upload test.json to S3

# Trigger this workflow on pushes to the main branch, but only if the specified file is modified
on:
  push:
    branches:
      - main
    paths:
      - test_client_project/data/test.json  # File path to watch for changes

jobs:
  upload_file_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your AWS region

      - name: Upload file to S3
        run: |
          aws s3 cp test_client_project/data/test.json s3://test-client-project/source_ip_file/test.json
